Item:
  STATE:
    1: NOT_LIVE
    2: LIVE
    3: OUT_OF_STOCK
    4: REMOVED

Order:
  STATE:
    1: CART
    2: COMPLETE
    99: ON_COMPLETE

Coupon:
  OPERATION:
    1: STARTS_WITH
    2: ENDS_WITH
    3: EQUALS
    4: MATCHES
    5: INCLUDES
    6: EXISTS
    7: IN_SET
    8: NOT_STARTS_WITH
    9: NOT_ENDS_WITH
    10: NOT_EQUALS
    11: NOT_MATCHES
    12: NOT_INCLUDES
    13: NOT_EXISTS
    14: NOT_IN_SET
    15: GREATER_THAN
    16: LESS_THAN
    17: GREATER_OR_EQUALS
    18: LESS_OR_EQUALS
    19: BETWEEN
